import PropertyPic1 from "../src/assets/images/image6.jpeg";
import PropertyPic2 from "../src/assets/images/image8.png";
import PropertyPic3 from "../src/assets/images/image6.jpeg";
import PropertyPic4 from "../src/assets/images/image8.png";
import PropertyPic5 from "../src/assets/images/image6.jpeg";

export const housesData = [
  {
    id: 1,
    listingType: "Buy",
    type: "Villa",
    image: PropertyPic1,
    heading: "Comfortable Apartment in Sint Maarten",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    price: " $1.000.000",
    address: "sYacht Club 12-3, 97150",
    country: "Sint Maarten",
    area: "Simpson Bay",
    surface: "1200 Sqft",
    bedrooms: "3 Bed",
    bathrooms: "2 Baths",
    furnished: "furnished",
  },
  {
    id: 2,
    type: "Appartment",
    listingType: "Buy",
    image: PropertyPic2,
    heading: "Comfortable Apartment in Sint Maarten",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    price: " $200.000",
    address: "Yacht Club 12-3, 97150",
    country: "Sint Maarten",
    area: "Simpson Bay",
    surface: "1200 Sqft",
    bedrooms: "3 Bed",
    bathrooms: "2 Baths",
    furnished: "unfurnished",
  },
  {
    id: 3,
    type: "Villa",
    listingType: "Rent",
    image: PropertyPic3,
    heading: "Comfortable Apartment in Sint Maarten",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    price: " $10.000",
    address: "Lot 644 Rue Dufy, 97150",
    country: "Sint Maarten",
    area: "Baie Rouge",
    surface: "1200 Sqft",
    bedrooms: "3 Beds",
    bathrooms: "1 Baths",
    furnished: "furnished",
  },
  {
    id: 4,
    type: "Villa",
    listingType: "Buy",
    image: PropertyPic4,
    heading: "Comfortable Villa in Sint Maarten",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    price: " $450.000",
    address: "Yacht Club 12-3, 97150",
    country: "Sint Maarten",
    area: "Simpson Bay",
    surface: "1200 Sqft",
    bedrooms: "3 Bed",
    bathrooms: "2 Baths",
    furnished: "unfurnished",
  },
  {
    id: 5,
    type: "House",
    listingType: "Rent",
    image: PropertyPic5,
    heading: "Comfortable Apartment in Sint Maarten",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    price: " $1.000.000",
    address: "Lot 644 Rue Dufy, 97150",
    country: "Sint Maarten",
    area: "Terres Bases",
    surface: "1200 Sqft",
    bedrooms: "3 Bed",
    bathrooms: "1 Baths",
    furnished: "furnished",
  },
  {
    id: 6,
    type: "Appartment",
    listingType: "Rent",
    image: PropertyPic2,
    heading: "Comfortable Apartment in Sint Maarten",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    price: " $2000",
    address: "Lot 644 Rue Dufy, 97150",
    country: "Sint Maarten",
    area: "Terres Basses",
    surface: "1200 Sqft",
    bedrooms: "3 Bed",
    bathrooms: "3 Baths",
    furnished: "furnished",
  },
  {
    id: 7,
    type: "Villa",
    listingType: "Buy",
    image: PropertyPic3,
    heading: "Comfortable Apartment in Sint Maarten",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    price: " $1.000.000",
    address: "Lot 644 Rue Dufy, 97150",
    country: "Sint Maarten",
    area: "Terres Basses",
    surface: "1200 Sqft",
    bedrooms: "3 Bed",
    bathrooms: "3 Baths",
    furnished: "unfurnished",
  },
  {
    id: 8,
    type: "Villa",
    listingType: "Buy",
    image: PropertyPic1,
    heading: "Comfortable Apartment in Sint Maarten",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    price: " $500.000",
    address: "Simpson Bay Yacht Club 12-3, 97150",
    country: "Sint Maarten",
    area: "Phillipsburg",
    surface: "1200 Sqft",
    bedrooms: "3 Bed",
    bathrooms: "3 Baths",
    furnished: "unfurnished",
  },
  {
    id: 9,
    type: "Villa",
    listingType: "Buy",
    image: PropertyPic1,
    heading: "Comfortable Apartment in Sint Maarten",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.",
    price: " $500.000",
    address: "Simpson Bay Yacht Club 12-3, 97150",
    country: "Sint Maarten",
    area: "Phillipsburg",
    surface: "1200 Sqft",
    bedrooms: "3 Bed",
    bathrooms: "3 Baths",
    furnished: "unfurnished",
  },
];
